### ISSUE TITLE
Duda inicio proyecto

### ISSUE THREAD

**Issue by alegrimminck** [pabpobar/Tarea1-Landing-Page#3]
Profe:
Para el desarrollo del proyecto ¿Tendremos que crear una branch en ESTE repositorio
o crear un repositorio nuevo y compartirle el archivo README?

Nota: Nosotros como grupo ya creamos un repo del proyecto [Pinche aquí](https://github.com/panchocorderos/conecta2-project)

**Comment by pabpobar** [comment]
Hola, este repo es para el **control** del avance del proyecto. Además, en una rama deben subir la información que se solicita en el readme. También lo utilizaremos para registrar toda la interacción que se produzca a lo largo del desarrollo.
